services:
    aerotrain_perception:
        image: aerotrain_perception #ricfr/aero_train_summer_school_day_1
        #command: tail -F anything
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
            args:
              - DOCKER_BUILDKIT=1
        container_name: aerotrain_perception
        network_mode: host
        working_dir: /root/catkin_ws
        privileged: true
        device_cgroup_rules:
            - "c 81:* rmw"
            - "c 189:* rmw"
        volumes:
            - $XAUTHORITY:$XAUTHORITY
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /dev:/dev
            #- ../exercises/2d_to_3d:/root/catkin_ws/src/2d_to_3d
            - ../solution/:/root/catkin_ws/src/
            - ../bag:/root/bag
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=$XAUTHORITY
