version: '3.3'

services:
    aerotrain_perception:
        image: aerotrain_perception
        build:
            context: .
            dockerfile: Dockerfile
            args:
              - DOCKER_BUILDKIT=1
        container_name: aerotrain_perception
        tty: true
        stdin_open: true
        privileged: true
        network_mode: host
        working_dir: /root/catkin_ws
        volumes:
            - $XAUTHORITY:$XAUTHORITY
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/sudoers.d:/etc/sudoers.d:ro
            - /dev:/dev
            #- /exercises:/root/catkin_ws/src/exercises
            - ../solution/:/root/catkin_ws/src/
            - ../bag:/root/bag
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - XAUTHORITY=$XAUTHORITY
        security_opt:
            - seccomp:unconfined
        runtime: nvidia
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]